import { createPair } from "../matchRules";
import type { Match, PlayerProfile } from "../types";

export const players: PlayerProfile[] = [
  {
    id: "player-zt",
    userId: "user-zt",
    displayName: "Zé Trovão",
    initials: "ZT",
    avatarUrl: "/presets/players/ze-trovao.svg",
    avatarPresetId: "ze-trovao",
    shirtNumber: 10,
    favoritePosition: "attacker",
    style: "Canhota pesada",
    nationality: "BRA",
    bio: "Se o pimba rolar, o gol é meu.",
    isAnonymous: false,
  },
  {
    id: "player-mg",
    displayName: "Magrão",
    initials: "MG",
    avatarUrl: "/presets/players/magrao.svg",
    avatarPresetId: "magrao",
    shirtNumber: 7,
    favoritePosition: "goalkeeper",
    style: "Muralha",
    nationality: "BRA",
    bio: "Fecha tudo e sai jogando.",
    isAnonymous: false,
  },
  {
    id: "player-bs",
    displayName: "Biscoito",
    initials: "BS",
    avatarUrl: "/presets/players/biscoito.svg",
    avatarPresetId: "biscoito",
    shirtNumber: 99,
    favoritePosition: "attacker",
    style: "Finalizador",
    nationality: "BRA",
    bio: "Um toque, uma provocação.",
    isAnonymous: false,
  },
  {
    id: "player-ru",
    displayName: "Russo",
    initials: "RU",
    avatarUrl: "/presets/players/russo.svg",
    avatarPresetId: "russo",
    shirtNumber: 8,
    favoritePosition: "goalkeeper",
    style: "Seguro",
    nationality: "BRA",
    bio: "Jogo simples ganha jogo.",
    isAnonymous: false,
  },
  {
    id: "player-td",
    displayName: "Tê Doido",
    initials: "TD",
    avatarUrl: "/presets/players/te-doido.svg",
    avatarPresetId: "te-doido",
    shirtNumber: 22,
    favoritePosition: "versatile",
    style: "Improviso",
    nationality: "BRA",
    bio: "Cada bola é uma surpresa.",
    isAnonymous: false,
  },
  {
    id: "player-nn",
    displayName: "Nanico",
    initials: "NN",
    avatarUrl: "/presets/players/nanico.svg",
    avatarPresetId: "nanico",
    shirtNumber: 11,
    favoritePosition: "attacker",
    style: "Ágil",
    nationality: "BRA",
    bio: "Baixo centro de gravidade.",
    isAnonymous: false,
  },
  {
    id: "player-pr",
    displayName: "Parca",
    initials: "PR",
    avatarUrl: "/presets/players/parca.svg",
    avatarPresetId: "parca",
    shirtNumber: 5,
    favoritePosition: "goalkeeper",
    style: "Parceiro",
    nationality: "BRA",
    bio: "Marca junto, comemora junto.",
    isAnonymous: false,
  },
  {
    id: "player-lm",
    displayName: "Leo & Mao",
    initials: "LM",
    avatarUrl: "/presets/players/leo-mao.svg",
    avatarPresetId: "leo-mao",
    shirtNumber: 17,
    favoritePosition: "versatile",
    style: "Anônimo operacional",
    nationality: "BRA",
    bio: "Participante convidado do grupo.",
    isAnonymous: true,
  },
];

const pairCafos = createPair("pair-cafos", "Os Cafofo", "player-mg", "player-zt");
const pairPerna = createPair("pair-perna", "Os Perna", "player-ru", "player-bs");
const pairTe = createPair("pair-te", "Time do Te", "player-pr", "player-td");
const pairNanico = createPair("pair-nanico", "Nanico & Parca", "player-nn", "player-pr");

export const matches: Match[] = [
  {
    id: "match-live",
    groupId: "group-trampo",
    kind: "friendly",
    status: "live",
    pairA: pairCafos,
    pairB: pairPerna,
    settings: { goalLimit: 3, timeLimitMinutes: 3, goldenGoal: true },
    startedAt: new Date(Date.now() - 96_000).toISOString(),
    goals: [
      {
        id: "goal-live-1",
        matchId: "match-live",
        pairId: pairCafos.id,
        playerId: "player-zt",
        position: "attacker",
        scoredAt: new Date(Date.now() - 70_000).toISOString(),
      },
      {
        id: "goal-live-2",
        matchId: "match-live",
        pairId: pairPerna.id,
        playerId: "player-bs",
        position: "attacker",
        scoredAt: new Date(Date.now() - 30_000).toISOString(),
      },
      {
        id: "goal-live-3",
        matchId: "match-live",
        pairId: pairCafos.id,
        playerId: "player-mg",
        position: "goalkeeper",
        scoredAt: new Date(Date.now() - 15_000).toISOString(),
      },
    ],
  },
  {
    id: "match-1",
    groupId: "group-trampo",
    kind: "friendly",
    status: "finished",
    pairA: pairCafos,
    pairB: pairNanico,
    settings: { goalLimit: 3, timeLimitMinutes: 3, goldenGoal: true },
    startedAt: "2026-06-19T15:10:00.000Z",
    finishedAt: "2026-06-19T15:14:00.000Z",
    winnerPairId: pairCafos.id,
    goals: [
      {
        id: "g1",
        matchId: "match-1",
        pairId: pairCafos.id,
        playerId: "player-zt",
        position: "attacker",
        scoredAt: "2026-06-19T15:10:20.000Z",
      },
      {
        id: "g2",
        matchId: "match-1",
        pairId: pairNanico.id,
        playerId: "player-nn",
        position: "attacker",
        scoredAt: "2026-06-19T15:11:20.000Z",
      },
      {
        id: "g3",
        matchId: "match-1",
        pairId: pairCafos.id,
        playerId: "player-mg",
        position: "goalkeeper",
        scoredAt: "2026-06-19T15:12:20.000Z",
      },
      {
        id: "g4",
        matchId: "match-1",
        pairId: pairCafos.id,
        playerId: "player-zt",
        position: "attacker",
        scoredAt: "2026-06-19T15:13:20.000Z",
      },
    ],
  },
  {
    id: "match-2",
    groupId: "group-trampo",
    kind: "tournament",
    tournamentId: "tournament-cafezinho",
    status: "finished",
    pairA: pairPerna,
    pairB: pairTe,
    settings: { goalLimit: 3, timeLimitMinutes: 3, goldenGoal: true },
    startedAt: "2026-06-18T15:10:00.000Z",
    finishedAt: "2026-06-18T15:13:00.000Z",
    winnerPairId: pairPerna.id,
    goals: [
      {
        id: "g5",
        matchId: "match-2",
        pairId: pairPerna.id,
        playerId: "player-bs",
        position: "attacker",
        scoredAt: "2026-06-18T15:10:20.000Z",
      },
      {
        id: "g6",
        matchId: "match-2",
        pairId: pairTe.id,
        playerId: "player-td",
        position: "attacker",
        scoredAt: "2026-06-18T15:11:20.000Z",
      },
      {
        id: "g7",
        matchId: "match-2",
        pairId: pairPerna.id,
        playerId: "player-ru",
        position: "goalkeeper",
        scoredAt: "2026-06-18T15:12:20.000Z",
      },
      {
        id: "g8",
        matchId: "match-2",
        pairId: pairPerna.id,
        playerId: "player-bs",
        position: "attacker",
        scoredAt: "2026-06-18T15:13:20.000Z",
      },
    ],
  },
];
